Repository Team-Questio/questio-api-server, pull requests merged in 2024-09, with the labels that each got.

#49 Response에 피드백 추가
  src/main/java/team_questio/questio/portfolio/application/PortfolioFacadeService.java
  src/main/java/team_questio/questio/portfolio/application/dto/QuestDetailInfo.java
  src/main/java/team_questio/questio/portfolio/domain/Quest.java
  src/main/java/team_questio/questio/portfolio/presentation/dto/QuestDetailResponse.java
  src/test/java/team_questio/questio/portfolio/application/QuestServiceTest.java
Labels: ✨ Feature, 📬 API

#51 컨테이너에서 사용중인 이미지 삭제
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#50 API 문서에 반환되는 오류 코드 추가
  src/main/java/team_questio/questio/common/exception/code/GPTError.java
  src/main/java/team_questio/questio/common/exception/code/PortfolioError.java
  src/main/java/team_questio/questio/gpt/service/GPTService.java
  src/main/java/team_questio/questio/portfolio/presentation/PortfolioApiController.java
  src/main/java/team_questio/questio/user/persentation/UserApiController.java
Labels: 📃 Docs

#53 테크 튜브 랜덤반환 API
  src/main/java/team_questio/questio/common/exception/code/VideoError.java
  src/main/java/team_questio/questio/video/application/VideoService.java
  src/main/java/team_questio/questio/video/application/dto/VideoInfo.java
  src/main/java/team_questio/questio/video/domain/Video.java
  src/main/java/team_questio/questio/video/persistence/VideoRepository.java
  src/main/java/team_questio/questio/video/presentation/VideoApiController.java
  src/main/java/team_questio/questio/video/presentation/VideoController.java
  src/main/java/team_questio/questio/video/presentation/dto/VideoResponse.java
Labels: ✨ Feature, 📬 API

#44 Feat/40 portfolio constraint
  src/main/java/team_questio/questio/common/exception/code/PortfolioError.java
  src/main/java/team_questio/questio/portfolio/application/PortfolioFacadeService.java
  src/main/java/team_questio/questio/portfolio/application/dto/GenerationInfo.java
  src/main/java/team_questio/questio/portfolio/presentation/PortfolioApiController.java
  src/main/java/team_questio/questio/portfolio/presentation/PortfolioController.java
  src/main/java/team_questio/questio/portfolio/presentation/dto/GenerationResponse.java
  src/main/java/team_questio/questio/user/application/UserService.java
  src/main/java/team_questio/questio/user/domain/User.java
Labels: ✨ Feature

#57 fix: 포트폴리오 업로드 횟수 기본값 오류 수정
  src/main/java/team_questio/questio/user/domain/User.java
Labels: 🐞 BugFix

#58 포트폴리오 업로드 잔여 횟수 반환 API
  src/main/java/team_questio/questio/portfolio/presentation/PortfolioApiController.java
  src/main/java/team_questio/questio/portfolio/presentation/PortfolioController.java
  src/main/java/team_questio/questio/user/persentation/UserApiController.java
  src/main/java/team_questio/questio/user/persentation/UserController.java
  src/main/java/team_questio/questio/user/persentation/dto/RemainingResponse.java
Labels: 📬 API

#61 GPT API 사용시 발생하는 JsonProcessingException 해결
  src/main/java/team_questio/questio/gpt/service/GPTService.java
Labels: 🐞 BugFix

#67 Feat/66 login info api
  src/main/java/team_questio/questio/user/application/UserService.java
  src/main/java/team_questio/questio/user/persentation/UserApiController.java
  src/main/java/team_questio/questio/user/persentation/UserController.java
  src/main/java/team_questio/questio/user/persentation/dto/UserInfoResponse.java
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#65 잔여 횟수 조회 시 횟수 차감하는 오류 수정
  src/main/java/team_questio/questio/common/exception/code/PortfolioError.java
  src/main/java/team_questio/questio/portfolio/application/PortfolioFacadeService.java
  src/main/java/team_questio/questio/security/application/PrincipleDetailService.java
  src/main/java/team_questio/questio/user/application/UserService.java
  src/main/java/team_questio/questio/user/domain/User.java
  src/main/java/team_questio/questio/user/persentation/UserController.java
Labels: 🐞 BugFix

#69 회원가입 시, username을 확인하는 로직을 수정했어요
  src/main/java/team_questio/questio/common/exception/code/AuthError.java
  src/main/java/team_questio/questio/security/application/AuthenticationService.java
  src/main/java/team_questio/questio/security/application/PrincipleDetailService.java
  src/main/java/team_questio/questio/security/config/SecurityServiceConfig.java
  src/main/java/team_questio/questio/user/application/UserService.java
  src/main/java/team_questio/questio/user/domain/User.java
  src/main/java/team_questio/questio/user/persistence/UserRepository.java
  src/test/java/team_questio/questio/security/application/PrincipleDetailServiceTest.java
  src/test/java/team_questio/questio/user/application/UserServiceTest.java
Labels: 🐞 BugFix
